### PR TITLE
Add Germane load description & related resource

### PR DESCRIPTION
**Pull request by txndai**

### CODE REVIEW

**Comment by zakirullin** [comment]
Hi there! Thanks for your contribution!

Even though I know about Germane load, I didn't include it in the handbook, not to overcomplicate things.

I am still not sure whether we should include this directly into the section. 

By introducing a concept of Germane load we increase reader's cognitive load by +1. The bad thing is, we don't use this term further on, thus I am not sure whether we should do this extensive taxonomy here 🤔

**Comment by txndai** [comment]
Pleasure :) 
Ah yeah, agreed. I do think that video I linked to is a helpful resource though, for those interested in further reading.
Do you think we can find a simple way to share that?

**Comment by zakirullin** [comment]
Yes! I believe we can leave a small footnote. 

Maybe we should collect all the links in the footnotes and the end of the handbook 🤔  

Because there are some links in the text alread.

**Comment by zakirullin** [comment]
For know I've added a small note about the existence of Germane Load.
https://github.com/zakirullin/cognitive-load/commit/3228dcfe9aab47ef114d6e997c9e4b141c8df580

Stil we can collect all the links on the matter down below

**Comment by txndai** [comment]
hey @zakirullin - I've added a footnote with related reading. Let me know if you're happy with the formatting
thanks for the suggestion😄

**Comment by zakirullin** [comment]
Thank you! Let me go through the whole video to see if it resonates with the handbook or not.

**Comment by zakirullin** [comment]
Decided not to cover it as for now

**Pull request closed without merging**
